import type { MetadataRoute } from 'next';
import { listCities, listUpcomingEvents, listVenues, todayIso } from '../lib/data.ts';

export const dynamic = 'force-static';

const BASE = process.env.LOPPEFUND_BASE_URL ?? 'https://jacobtop-tcg.github.io/loppefund';

export default function sitemap(): MetadataRoute.Sitemap {
  const events = listUpcomingEvents(180);
  const venues = listVenues();
  // Every page is regenerated by the twice-daily crawl+build, so the build date
  // is an honest <lastmod> — it tells crawlers the whole set is refreshed daily.
  const lastModified = todayIso();
  return [
    { url: BASE, lastModified, changeFrequency: 'daily', priority: 1 },
    // The highest-intent searches (time- and place-based) get their own indexable pages.
    { url: `${BASE}/i-dag`, lastModified, changeFrequency: 'daily', priority: 0.9 },
    { url: `${BASE}/i-weekenden`, lastModified, changeFrequency: 'daily', priority: 0.9 },
    { url: `${BASE}/naer-mig`, lastModified, changeFrequency: 'daily', priority: 0.9 },
    { url: `${BASE}/byer`, lastModified, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${BASE}/kilder`, lastModified, changeFrequency: 'weekly', priority: 0.5 },
    ...listCities().map((c) => ({
      url: `${BASE}/by/${c.slug}`,
      lastModified,
      changeFrequency: 'daily' as const,
      priority: 0.8,
    })),
    ...events.map((e) => ({
      url: `${BASE}/marked/${e.slug}`,
      lastModified,
      changeFrequency: 'daily' as const,
      priority: 0.7,
    })),
    ...venues.map((v) => ({
      url: `${BASE}/sted/${v.slug}`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: 0.5,
    })),
  ];
}
