import type { MetadataRoute } from 'next';
import {
  listCities,
  listUpcomingEvents,
  listVenues,
  todayIso,
  UPCOMING_HORIZON_DAYS,
} from '../lib/data.ts';

export const dynamic = 'force-static';

const BASE = process.env.LOPPEFUND_BASE_URL ?? 'https://jacobtop-tcg.github.io/loppefund';

export default function sitemap(): MetadataRoute.Sitemap {
  // Same horizon as the pages themselves, so every market with a real page is in
  // the sitemap (and none in the sitemap 404s).
  const events = listUpcomingEvents(UPCOMING_HORIZON_DAYS);
  const venues = listVenues();
  // Every page is regenerated by the twice-daily crawl+build, so the build date
  // is an honest <lastmod> — it tells crawlers the whole set is refreshed daily.
  const lastModified = todayIso();
  return [
    { url: BASE, lastModified, changeFrequency: 'daily', priority: 1 },
    // The highest-intent searches (time- and place-based) get their own indexable pages.
    { url: `${BASE}/i-dag`, lastModified, changeFrequency: 'daily', priority: 0.9 },
    { url: `${BASE}/i-weekenden`, lastModified, changeFrequency: 'daily', priority: 0.9 },
    { url: `${BASE}/naer-mig`, lastModified, changeFrequency: 'daily', priority: 0.9 },
    { url: `${BASE}/byer`, lastModified, changeFrequency: 'weekly', priority: 0.8 },
    // The hidden-place cluster. It was unreachable: /tip-perle linked only from
    // /skjulte-steder and /skjulte-steder only from /tip-perle, with nothing
    // pointing in and neither in the sitemap. A tip form nobody can reach
    // collects no tips — which is exactly what happened.
    { url: `${BASE}/skjulte-steder`, lastModified, changeFrequency: 'daily', priority: 0.8 },
    { url: `${BASE}/tip-perle`, lastModified, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${BASE}/kilder`, lastModified, changeFrequency: 'weekly', priority: 0.5 },
    ...listCities().map((c) => ({
      url: `${BASE}/by/${c.slug}`,
      lastModified,
      changeFrequency: 'daily' as const,
      priority: 0.8,
    })),
    ...events.map((e) => ({
      url: `${BASE}/marked/${e.slug}`,
      lastModified,
      changeFrequency: 'daily' as const,
      priority: 0.7,
    })),
    ...venues.map((v) => ({
      url: `${BASE}/sted/${v.slug}`,
      lastModified,
      changeFrequency: 'weekly' as const,
      priority: 0.5,
    })),
  ];
}
